[project]
name = "bulk-data-service"
version = "1.4.1"
requires-python = ">= 3.12.6"
readme = "README.md"
dependencies = [
    "azure-servicebus~=7.14",
    "azure-storage-blob~=12.25",
    "chardet~=5.2",
    "libsuitecrm @ git+https://github.com/IATI/iati-registry-libsuitecrm.git",
    "prometheus-client~=0.22",
    "psycopg[binary,pool]~=3.2",
    "requests~=2.23",
    "toml~=0.10",
    "yoyo-migrations~=9.0",
]


[project.optional-dependencies]
dev = [
    "black~=25.1",
    "flake8~=7.3",
    "flake8-pyproject~=1.2",
    "isort~=6.0",
    "jsonschema~=4.25",
    "mypy~=1.17",
    "pip-tools~=7.4",
    "pytest-asyncio~=1.0",
    "python-dotenv~=1.1",
    "pytest~=8.4",
    "pytest-watcher~=0.4",
    "responses~=0.25",
    "types-requests~=2.32",
    "types-toml~=0.10",
]


[tool.pip-tools]
strip-extras = true


[tool.pytest.ini_options]
testpaths = ["tests/unit", "tests/integration"]
addopts = [
    "--import-mode=importlib"
]
pythonpath = [
  "src", "tests"
]
filterwarnings = [
    "ignore::DeprecationWarning:yoyo.*:",  # ignore deprecations from all modules
    "default::DeprecationWarning:bulk_data_service.*:",  # except the app
]

[tool.isort]
py_version = "312"
extend_skip = ['__pycache__', '.mypy_cache', '.ve', '.venv', '.vagrant-ve']
skip_gitignore = true
src_paths = ['src', 'tests']
line_length = 119
profile = "black"


[tool.mypy]
files="src/"
mypy_path="tests/"


[tool.flake8]
max-line-length = 119
extend_ignore = ['E203', 'W503', 'E275']
exclude = ['__pycache__', '.mypy_cache', '.pytest_cache', '.ve', '.venv', '.vagrant-ve']
max_complexity = 7


[tool.black]
line-length = 119
target-version = ['py312']
include='''src/.*/*.py$'''
