--
-- depends:

-- auto-generated definition
create table iati_datasets
(
    id                                              uuid         not null,
    name                                            varchar      not null,
    publisher_id                                    uuid         not null,
    publisher_name                                  varchar      not null,
    type                                            varchar      not null,
    source_url                                      varchar,
    hash                                            varchar,
    hash_excluding_generated_timestamp              varchar,
    last_update_check                               timestamp with time zone,
    last_head_attempt                               timestamp with time zone,
    last_head_http_status                           smallint,
    head_error_message                              varchar,
    last_download_attempt                           timestamp with time zone,
    last_download_http_status                       smallint,
    last_successful_download                        timestamp with time zone,
    last_verified_on_server                         timestamp with time zone,
    download_error_message                          varchar,
    content_modified                                timestamp with time zone,
    content_modified_excluding_generated_timestamp  timestamp with time zone,
    server_header_last_modified                     timestamp with time zone,
    server_header_etag                              varchar
);

comment on column iati_datasets.name is 'the short name of the dataset';

comment on column iati_datasets.type is 'type of the IATI XML file: activity or organisation';

comment on column iati_datasets.source_url is 'the source url of dataset on the publisher website';

comment on column iati_datasets.hash is 'hash of dataset as generated by Bulk Data Service';

comment on column iati_datasets.hash_excluding_generated_timestamp is 'hash of dataset content excluding the generated-datetime attribute as generated by Bulk Data Service';

comment on column iati_datasets.last_update_check is 'the last time a the status of the dataset was updated or checked';

comment on column iati_datasets.last_head_attempt is 'the last time an HTTP HEAD request was attempted';

comment on column iati_datasets.last_head_http_status is 'the HTTP status code of the last HEAD request';

comment on column iati_datasets.head_error_message is 'the error message of the last HEAD request (if any)';

comment on column iati_datasets.last_download_attempt is 'the last time a full download of dataset was attempted';

comment on column iati_datasets.last_download_http_status is 'the HTTP status code of the last download attempt';

comment on column iati_datasets.last_successful_download is 'the time of the last successful download of the dataset';

comment on column iati_datasets.last_verified_on_server is 'the last time data was successfully downloaded or confirmed as unchanged by successful HEAD request';

comment on column iati_datasets.download_error_message is 'the error message of the last full download attempt (if any)';

comment on column iati_datasets.content_modified is 'the time at which any part of the IATI file changed';

comment on column iati_datasets.content_modified_excluding_generated_timestamp is 'the time at which the substantive contents of the file changed, excluding the ''generated-datetime'' attribute ';

comment on column iati_datasets.server_header_last_modified is 'the contents of the Last-Modified header on source server hosting the dataset ';

comment on column iati_datasets.server_header_etag is 'the contents of the ETag header on source server hosting the dataset ';

alter table iati_datasets
    owner to bds;

create unique index iati_datasets_pk
    on iati_datasets (id);

