from utilities.misc import get_hash, get_hash_excluding_generated_timestamp


def test_get_hash():

    # this is the actual content of one of the smallest IATI Activity XML files.
    # Do not change the number of empty lines.
    yiplActivitiesXmlFile = """<?xml version="1.0"?>
<iati-activities version="2.03" generated-datetime="2024-05-03T08:47:49+00:00">
<!--Generated By AidStream-->











</iati-activities>
"""

    hash = get_hash(yiplActivitiesXmlFile)

    assert(hash == "3486d4cee556d2584020bed2c86305465b8b3880")


def test_get_hash_excluding_generated_timestamp():

    # this is the actual content of one of the smallest IATI Activity XML files.
    # Do not change the number of empty lines.
    yiplActivitiesXmlFile = """<?xml version="1.0"?>
<iati-activities version="2.03" generated-datetime="2024-05-03T08:47:49+00:00">
<!--Generated By AidStream-->











</iati-activities>
"""

    hash = get_hash_excluding_generated_timestamp(yiplActivitiesXmlFile)

    assert(hash == "759eaa39276381f3fc146232cefd2111a2abc199")
